[package]
name = "web3"
version = "0.1.0"
authors = ["nagaraj <nagarajmanjunath22@gmail.com>"]
edition = "2018"

[dependencies]
blockchain = {path = "../blockchain"}


[dependencies.parity-rpc]
git = "https://github.com/b00f/parity-ethereum.git"



